/robocon_tf_broadcaster:
  ros__parameters:
    # 雷达相对于底盘物理中心的安装偏移 [x, y, z, roll, pitch, yaw] (单位：米、弧度)
    # 例如：雷达装在车子物理中心前方 0.1m，上方 0.3m 处
    lidar_offset: [0.1, 0.0, 0.3, 0.0, 0.0, 0.0]

    # 色度传感器相对于底盘物理中心的安装偏移 [x, y, z, roll, pitch, yaw]
    # 例如：色度传感器装在车子物理中心后方 0.15m，右方 0.05m，贴近地面 0.02m 处
    sensor_offset: [-0.15, -0.05, -0.02, 0.0, 0.0, 0.0]
